"""Printing

Revision ID: 00c8551c135b
Revises: d983b085b988
Create Date: 2025-07-25 12:00:49.991126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c8551c135b'
down_revision: Union[str, None] = 'd983b085b988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cerbo_measurements', sa.Column('soc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cerbo_measurements', 'soc')
    # ### end Alembic commands ###
