"""migration for grossing statuses

Revision ID: 0cddf1eb4f41
Revises: 5dc5b4025f63
Create Date: 2025-08-19 12:39:40.054007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cddf1eb4f41'
down_revision: Union[str, None] = '5dc5b4025f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_signature_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('doctor_cor_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_signature_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )

    op.execute("ALTER TYPE grossing_status ADD VALUE 'CREATED'")
    op.execute("ALTER TYPE grossing_status ADD VALUE 'IN_SIGNING_STATUS'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_signature_sessions')
    op.execute(
        "ALTER TYPE grossing_status DROP VALUE 'CREATED'")
    op.execute(
        "ALTER TYPE grossing_status DROP VALUE 'IN_SIGNING_STATUS'")
    # ### end Alembic commands ###
