"""test 1 migration v.1_0_0_3

Revision ID: 38b64534968d
Revises: 94ce2a174208
Create Date: 2025-06-23 11:12:42.500940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b64534968d'
down_revision: Union[str, None] = '94ce2a174208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_managers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('energy_manager_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('lab_assistants_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['energy_manager_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('energy_manager_cor_id')
    )
    op.create_table('lab_assistants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_assistant_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('lab_assistants_photo', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['lab_assistant_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_assistant_cor_id')
    )
    op.create_table('lawyers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lawyer_cor_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lawyer_cor_id'], ['users.cor_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_cor_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('immunohistochemical_profile', sa.Text(), nullable=True),
    sa.Column('molecular_genetic_profile', sa.Text(), nullable=True),
    sa.Column('pathomorphological_diagnosis', sa.Text(), nullable=True),
    sa.Column('icd_code', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('attached_glass_ids', sa.ARRAY(sa.String(length=36)), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('clinic_patient_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_status_for_clinic', sa.Enum('registered', 'diagnosed', 'under_treatment', 'hospitalized', 'discharged', 'died', 'in_process', 'referred_for_additional_consultation', 'awaiting_report', 'completed', 'error', name='patientclinicstatus'), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('signature_name', sa.String(length=255), nullable=True),
    sa.Column('signature_scan_data', sa.LargeBinary(), nullable=True),
    sa.Column('signature_scan_type', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_signature_id', sa.String(length=36), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['doctor_signature_id'], ['doctor_signatures.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('pathohistological_conclusion', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('microdescription', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('general_macrodescription', sa.Text(), nullable=True))
    op.drop_index('ix_cases_case_code', table_name='cases')
    op.create_index(op.f('ix_cases_case_code'), 'cases', ['case_code'], unique=True)
    op.add_column('doctors', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.drop_column('doctors', 'surname')
    op.add_column('user_sessions', sa.Column('access_token', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'access_token')
    op.add_column('doctors', sa.Column('surname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'middle_name')
    op.drop_index(op.f('ix_cases_case_code'), table_name='cases')
    op.create_index('ix_cases_case_code', 'cases', ['case_code'], unique=False)
    op.drop_column('cases', 'general_macrodescription')
    op.drop_column('cases', 'microdescription')
    op.drop_column('cases', 'pathohistological_conclusion')
    op.drop_table('report_signatures')
    op.drop_table('doctor_signatures')
    op.drop_table('clinic_patient_statuses')
    op.drop_table('reports')
    op.drop_table('lawyers')
    op.drop_table('lab_assistants')
    op.drop_table('energy_managers')
    # ### end Alembic commands ###
