"""svs_dicom

Revision ID: 5dc5b4025f63
Revises: 00c8551c135b
Create Date: 2025-08-14 10:33:24.894487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc5b4025f63'
down_revision: Union[str, None] = '00c8551c135b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecg_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время сохранения записи в БД'),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecg_measurements_user_id'), 'ecg_measurements', ['user_id'], unique=False)
    op.add_column('glasses', sa.Column('scan_url', sa.String(), nullable=True))
    op.add_column('glasses', sa.Column('preview_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glasses', 'preview_url')
    op.drop_column('glasses', 'scan_url')
    op.drop_index(op.f('ix_ecg_measurements_user_id'), table_name='ecg_measurements')
    op.drop_table('ecg_measurements')
    # ### end Alembic commands ###
