"""second migration  v1.0.0.2

Revision ID: d74e2f053b1f
Revises: ec8ee64f0035
Create Date: 2025-05-30 10:31:56.752371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74e2f053b1f'
down_revision: Union[str, None] = 'ec8ee64f0035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False, comment='ID связанного кейса'),
    sa.Column('case_number', sa.String(), nullable=False, comment='Номер кейса'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания направления'),
    sa.Column('research_type', sa.Enum('CYTOLOGY', 'HISTOPATHOLOGY', 'IMMUNOHISTOCHEMISTRY', 'FISH_CISH', name='studytype'), nullable=True, comment='Вид исследования'),
    sa.Column('container_count', sa.Integer(), nullable=True, comment='Фактическое количество контейнеров'),
    sa.Column('medical_card_number', sa.String(), nullable=True, comment='Номер медкарты'),
    sa.Column('clinical_data', sa.Text(), nullable=True, comment='Клинические данные'),
    sa.Column('clinical_diagnosis', sa.String(), nullable=True, comment='Клинический диагноз'),
    sa.Column('medical_institution', sa.String(), nullable=True, comment='Медицинское учреждение'),
    sa.Column('department', sa.String(), nullable=True, comment='Отделение'),
    sa.Column('attending_doctor', sa.String(), nullable=True, comment='Лечащий врач'),
    sa.Column('doctor_contacts', sa.String(), nullable=True, comment='Контакты врача'),
    sa.Column('medical_procedure', sa.String(), nullable=True, comment='Медицинская процедура'),
    sa.Column('final_report_delivery', sa.Text(), nullable=True, comment='Финальный репорт отправить'),
    sa.Column('issued_at', sa.DateTime(), nullable=True, comment='Выдано (дата)'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_referrals_case_number'), 'referrals', ['case_number'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('referral_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False, comment='ID связанного направления'),
    sa.Column('filename', sa.String(), nullable=False, comment='Имя файла'),
    sa.Column('content_type', sa.String(), nullable=False, comment='Тип содержимого (например, image/jpeg, application/pdf)'),
    sa.Column('file_data', sa.LargeBinary(), nullable=False, comment='Бинарные данные файла'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_attachments_id'), 'referral_attachments', ['id'], unique=False)
    op.add_column('doctors', sa.Column('place_of_registration', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('macro_description', sa.Text(), nullable=True))
    op.add_column('user_sessions', sa.Column('jti', sa.String(), nullable=True, comment='JTI последнего Access токена, выданного для этой сессии'))
    op.create_unique_constraint(None, 'user_sessions', ['jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_column('user_sessions', 'jti')
    op.drop_column('samples', 'macro_description')
    op.drop_column('doctors', 'place_of_registration')
    op.drop_index(op.f('ix_referral_attachments_id'), table_name='referral_attachments')
    op.drop_table('referral_attachments')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_case_number'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
