# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий с полной историей
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 2️⃣ Формируем уникальную версию
    - name: Set version
      id: version
      run: |
        # Короткий хэш последнего коммита
        SHORT_COMMIT=$(git rev-parse --short HEAD)
        # Текущее время (год, месяц, день, час, минута, секунда)
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        # Формируем версию
        VERSION="0.1.${TIMESTAMP}-${SHORT_COMMIT}"
        # Передаём в environment
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        # Записываем в version.py для фронта
        echo "__version__='${VERSION}'" > cor_pass/version.py
        echo "Version file content:"
        cat cor_pass/version.py

    # 3️⃣ Устанавливаем зависимости
    - name: Install dependencies
      run: pip install -r requirements.txt

    # 4️⃣ Деплой (можно добавить свои команды)
    - name: Deploy
      run: |
        echo "Deploying version $VERSION"
        # Пример: ssh user@server "cd /app && git pull && systemctl restart app"
